In [ ]:
#This resizes the ndarray

In [4]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

a.shape = (3,2)

a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
import numpy as np

a = np.array([[13,26,33],[4,35,76]])

print(a.shape)

(2, 3)


In [ ]:
#Write a program to illustrate the use of reshaping or resizing the array using numpy

In [2]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

ab = np.reshape = (3,2)

print(a,ab)

[[1 2 3]
 [4 5 6]] (3, 2)


In [12]:
import numpy as np
a = np.arange(45)
b = a.reshape(3,3,5)
print(b.ndim)
print(b)

3
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [3]:
import numpy as np
x = np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

1
