In [1]:
import numpy as np


In [3]:
d=np.array([2,4,5,6,7,8,9,23,45,78])

d

array([ 2,  4,  5,  6,  7,  8,  9, 23, 45, 78])

In [4]:
list=(list(range(10000)))
d=np.array(list)
d

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [9]:
arr = np.array([[1,3,4],[3,5,8],[7,9,5]])
arr

array([[1, 3, 4],
       [3, 5, 8],
       [7, 9, 5]])

In [10]:
arr.size

9

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr.shape

(3, 3)

In [13]:
arr.ndim

2

In [14]:
type(arr)

numpy.ndarray

In [19]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [29]:
arr = np.linspace(5,15,2)
arr

array([ 5., 15.])

In [30]:
arr = np.array([2,4,5,6,7])
np.append(arr,12)

array([ 2,  4,  5,  6,  7, 12])

In [32]:
list = [2,3,4,5,6]
n=np.append(list,19)
n

array([ 2,  3,  4,  5,  6, 19])

In [34]:
np.delete(list,1)

array([2, 4, 5, 6])

In [35]:
l=[2,7,5,3,9,1,4]
np.sort(l)

array([1, 2, 3, 4, 5, 7, 9])

In [43]:
arr=np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
np.reshape(arr,(6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
np.reshape(arr,(2,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [48]:
l = [2,3,4,1,6,7,6,7,3,8]
a = np.reshape(l,(2,5))
a

array([[2, 3, 4, 1, 6],
       [7, 6, 7, 3, 8]])

In [49]:
type(a)

numpy.ndarray

In [54]:
l=[[2,3,5],[6,7,3]]
l[1][2]

3